In [101]:
# Dependencies
import os
import sys
import re 
import pandas as pd
import numpy as np
from pymongo import MongoClient
import shutil
pd.options.mode.chained_assignment = None  # default='warn'

In [126]:
# Set directory file paths
filepath = os.path.join(".", "Resources/State/Demographic", "ACS_13_5YR_S0102_with_ann.csv")

In [127]:
total_state_df = pd.read_csv(filepath, skiprows=[0])
# Split the extension from the path and normalise it to lowercase.
# ext = os.path.splitext(filepath)[-1].lower()
# excel = os.path.splitext(filepath)[0].lower()

# state_df["Year"] = "2009"
# state_df["Year"] = int(excel.split("_")[-1])
total_state_df.head()

,Id,Id2,Geography,Total; Estimate; Total population,Total; Margin of Error; Total population,60 years and over; Estimate; Total population,60 years and over; Margin of Error; Total population,Total; Estimate; SEX AND AGE - Male,Total; Margin of Error; SEX AND AGE - Male,60 years and over; Estimate; SEX AND AGE - Male,...,60 years and over; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Less than 30 percent,60 years and over; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Less than 30 percent,Total; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,Total; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,60 years and over; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,60 years and over; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,Total; Estimate; GROSS RENT - Median gross rent (dollars),Total; Margin of Error; GROSS RENT - Median gross rent (dollars),60 years and over; Estimate; GROSS RENT - Median gross rent (dollars),60 years and over; Margin of Error; GROSS RENT - Median gross rent (dollars)
0,0400000US01,1,Alabama,4799277,*****,966454,2674,48.5,0.1,44.1,...,56.0,1.0,44.8,0.6,44.0,1.0,705,3,569,9
1,0400000US02,2,Alaska,720316,*****,96430,985,52.2,0.1,50.3,...,52.6,2.7,40.6,0.9,47.4,2.7,1098,13,846,23
2,0400000US04,4,Arizona,6479703,*****,1294109,3052,49.7,0.1,46.1,...,46.1,0.9,47.5,0.4,53.9,0.9,896,4,836,8
3,0400000US05,5,Arkansas,2933369,*****,601493,2218,49.1,0.1,44.9,...,58.1,1.3,43.0,0.6,41.9,1.3,661,4,565,9
4,0400000US06,6,California,37659181,*****,6360929,7359,49.7,0.1,45.0,...,40.2,0.3,54.1,0.2,59.8,0.3,1224,2,994,4

In [128]:
demo_state_cols_df = total_state_df.filter(regex="RACE AND HISPANIC OR LATINO ORIGIN")
demo_state_df = total_state_df.filter(regex="Geography")

demo_state_df.head()
demo_state_cols_df.head()

,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races
0,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,0.1,...,0.0,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1
1,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,0.1,...,0.5,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3
2,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,0.1,...,0.1,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1
3,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,0.1,...,0.0,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1
4,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,0.1,...,0.3,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1

In [129]:
total_demo_state_df = pd.concat([demo_state_df, demo_state_cols_df], axis=1)

total_demo_state_df.head()

,Geography,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,0.0,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,0.5,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,0.1,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,0.0,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,0.3,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1

In [130]:
total_demo_state_df["Year"] = "2013"
# state_df["Year"] = int(excel.split("_")[-1])
total_demo_state_df.head()

,Geography,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Year
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1,2013
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3,2013
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1,2013
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1,2013
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1,2013

In [131]:
total_demo_state_df.columns

Index(['Geography',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       'Year'],
      dtype='object')

In [132]:
# Pass sheet title to description & country to hierachy columns for each row
total_demo_state_df["Hierarchy"] = "State"
# state_df["H_Name"] = list(state_df)[2]
# state_df["Population_Number"] = list(state_df)[3]
total_demo_state_df["Category"] = "Ethnicity"
total_demo_state_df["SubCategory"] = "Black or African American"
total_demo_state_df["Description"] = "Percentage"
total_demo_state_df["Notes"] = ""

# Rename 1st two columns
mapping = {total_demo_state_df.columns[0]: 'H_Name', total_demo_state_df.columns[9]: 'Population_Number'}
state_df = total_demo_state_df.rename(columns=mapping)

state_df.head()

,H_Name,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Population_Number,...,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Year,Hierarchy,Category,SubCategory,Description,Notes
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,1.5,0.1,0.8,0.1,2013,State,Ethnicity,Black or African American,Percentage,
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,7.9,0.2,2.4,0.3,2013,State,Ethnicity,Black or African American,Percentage,
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,3.0,0.1,1.0,0.1,2013,State,Ethnicity,Black or African American,Percentage,
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,2.0,0.1,1.1,0.1,2013,State,Ethnicity,Black or African American,Percentage,
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,4.3,0.1,1.9,0.1,2013,State,Ethnicity,Black or African American,Percentage,

In [109]:
final_state_df = state_df[['Year', 'Hierarchy', 'H_Name', 'Population_Number', 'Category', 'SubCategory', 'Description', 'Notes']]
final_state_df.head()

,Year,Hierarchy,H_Name,Population_Number,Category,SubCategory,Description,Notes
0,2017,State,Alabama,68.4,Ethnicity,White,Percentage,
1,2017,State,Alaska,65.3,Ethnicity,White,Percentage,
2,2017,State,Arizona,77.5,Ethnicity,White,Percentage,
3,2017,State,Arkansas,77.3,Ethnicity,White,Percentage,
4,2017,State,California,60.6,Ethnicity,White,Percentage,

In [110]:
# # This function move footnotes to specific cells and remove Nan rows
# def Update_FootNotes(_df):
#     _df["Notes"] = "" 
#     # Get all the 1st character in column, extract only digit & get the max    
#     nlist = _df['Notes'].str[0].tolist()
#     results = [int(n) for n in nlist if n.isdigit()]
#     m = max(results)
#     f = m
#     # Loop thru the max and update footnote to specific row cell
#     for i in range(m):
#         n = (i+1)
#         fn = f'-{f}'
#         #         print(n)
#         #         print(fn)
#         footnote = _df.iloc[int(fn), 0].replace(f"{n} ", "")
# #         print(footnote)
#         _df.loc[_df.Notes.str.contains(str(n)), "Notes"] = f'Footnotes {n}: {footnote}'
#         f-=1
#     # -----------------------------------------------    
#     # Drop all NaN rows
#     _df = _df.dropna()
#     # Remove digit from column
#     pattern = '[0-9]'
#     _df.Notes = [re.sub(pattern, '', row.Notes) for i, row in _df.iterrows()] 
        
#     return _df

In [111]:
# Pass footnote to specific cells and clean data
# state_df = Update_FootNotes(state_df)
# Convert Column to Integer
# state_df[""] = state_df[""].astype(int)
# Some excel sheet has lowercase
# state_df.loc[state_df[""] == "", ""] = ""
# state_df.reset_index(drop=True,inplace=True)

In [112]:
final_state_df["Created_By"] = "Charleen"
final_state_df["Created_Date"] = pd.datetime.now().strftime("%m-%d-%Y %I:%M:%S")
final_state_df.head()

,Year,Hierarchy,H_Name,Population_Number,Category,SubCategory,Description,Notes,Created_By,Created_Date
0,2017,State,Alabama,68.4,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:55:45
1,2017,State,Alaska,65.3,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:55:45
2,2017,State,Arizona,77.5,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:55:45
3,2017,State,Arkansas,77.3,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:55:45
4,2017,State,California,60.6,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:55:45

In [113]:
# # Create notes column and copy footnotes to Notes for selective row by locating the row cell with the footnote
# country_df["Notes"] = ""      
# country_df.loc[country_df.Crime_Type.str.contains('1'), "Notes"] = f'Footnotes: {country_df.iloc[-2, 0].replace("1 ", "")}'
# country_df.loc[country_df.Crime_Type.str.contains('2'), "Notes"] = f'Footnotes: {country_df.iloc[-1, 0].replace("2 ", "")}'
# # Drop all NaN rows
# country_df = country_df.dropna()
# # Remove digit from column
# pattern = '[0-9]'
# country_df.Crime_Type = [re.sub(pattern, '', row.Crime_Type) for i, row in country_df.iterrows()] 
final_state_df.count()

Year                 51
Hierarchy            51
H_Name               51
Population_Number    51
Category             51
SubCategory          51
Description          51
Notes                51
Created_By           51
Created_Date         51
dtype: int64

In [114]:
final_state_df.dtypes

Year                  object
Hierarchy             object
H_Name                object
Population_Number    float64
Category              object
SubCategory           object
Description           object
Notes                 object
Created_By            object
Created_Date          object
dtype: object

In [115]:
final_state_df['Year'] = final_state_df['Year'].astype(int)

In [116]:
final_state_df = final_state_df.astype({'Year': 'int64'})

In [117]:
final_state_df.dtypes

Year                   int64
Hierarchy             object
H_Name                object
Population_Number    float64
Category              object
SubCategory           object
Description           object
Notes                 object
Created_By            object
Created_Date          object
dtype: object

In [118]:
final_state_df['H_Name'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [119]:
len(final_state_df['H_Name'].unique())

51

In [120]:
final_state_df.shape

(51, 10)

In [121]:
final_state_df.describe()

         Year  Population_Number
count    51.0          51.000000
mean   2017.0          76.241176
std       0.0          13.605972
min    2017.0          25.100000
25%    2017.0          68.400000
50%    2017.0          77.800000
75%    2017.0          85.400000
max    2017.0          94.600000

In [122]:
# Set connection to database
client = MongoClient("mongodb+srv://admin:admin123@janie-test-vcn3t.mongodb.net/test?retryWrites=true")
db = client.consultant

In [123]:
records = final_state_df.to_dict('records')
[db.population.update_many({"Year": row["Year"], "Hierarchy": row["Hierarchy"], "H_Name": row["H_Name"], "Population_Number": row["Population_Number"], "Category": row["Category"], "SubCategory": row["SubCategory"], "Description": row["Description"], "Notes": row["Notes"], "Created_By": row["Created_By"], "Created_Date": row["Created_Date"]}, {'$set': row}, upsert=True) for row in records]

[<pymongo.results.UpdateResult at 0x1d655afe448>,
 <pymongo.results.UpdateResult at 0x1d655b42708>,
 <pymongo.results.UpdateResult at 0x1d655abbf08>,
 <pymongo.results.UpdateResult at 0x1d655b277c8>,
 <pymongo.results.UpdateResult at 0x1d655b03cc8>,
 <pymongo.results.UpdateResult at 0x1d655b09848>,
 <pymongo.results.UpdateResult at 0x1d655b1ec08>,
 <pymongo.results.UpdateResult at 0x1d655b1ebc8>,
 <pymongo.results.UpdateResult at 0x1d655b1e7c8>,
 <pymongo.results.UpdateResult at 0x1d655b09208>,
 <pymongo.results.UpdateResult at 0x1d655abec08>,
 <pymongo.results.UpdateResult at 0x1d655b0b048>,
 <pymongo.results.UpdateResult at 0x1d655b0ba48>,
 <pymongo.results.UpdateResult at 0x1d655abec88>,
 <pymongo.results.UpdateResult at 0x1d655b18388>,
 <pymongo.results.UpdateResult at 0x1d655af9608>,
 <pymongo.results.UpdateResult at 0x1d655af9108>,
 <pymongo.results.UpdateResult at 0x1d655af5308>,
 <pymongo.results.UpdateResult at 0x1d655af5f48>,
 <pymongo.results.UpdateResult at 0x1d655a57888>,
 <pymongo.results.UpdateResult at 0x1d655b05548>,
 <pymongo.results.UpdateResult at 0x1d655b05048>,
 <pymongo.results.UpdateResult at 0x1d655a52b48>,
 <pymongo.results.UpdateResult at 0x1d655b0e388>,
 <pymongo.results.UpdateResult at 0x1d655b0e548>,
 <pymongo.results.UpdateResult at 0x1d655a5a588>,
 <pymongo.results.UpdateResult at 0x1d655b12d08>,
 <pymongo.results.UpdateResult at 0x1d655b12cc8>,
 <pymongo.results.UpdateResult at 0x1d655b13a88>,
 <pymongo.results.UpdateResult at 0x1d655b1c9c8>,
 <pymongo.results.UpdateResult at 0x1d655b1c588>,
 <pymongo.results.UpdateResult at 0x1d655ace3c8>,
 <pymongo.results.UpdateResult at 0x1d655ace5c8>,
 <pymongo.results.UpdateResult at 0x1d655b49288>,
 <pymongo.results.UpdateResult at 0x1d655b49e08>,
 <pymongo.results.UpdateResult at 0x1d655b4c708>,
 <pymongo.results.UpdateResult at 0x1d655b4cd08>,
 <pymongo.results.UpdateResult at 0x1d655b30bc8>,
 <pymongo.results.UpdateResult at 0x1d655b30048>,
 <pymongo.results.UpdateResult at 0x1d655b4ec88>,
 <pymongo.results.UpdateResult at 0x1d655b4ed88>,
 <pymongo.results.UpdateResult at 0x1d655b51308>,
 <pymongo.results.UpdateResult at 0x1d655b561c8>,
 <pymongo.results.UpdateResult at 0x1d655b56548>,
 <pymongo.results.UpdateResult at 0x1d655b580c8>,
 <pymongo.results.UpdateResult at 0x1d655b58808>,
 <pymongo.results.UpdateResult at 0x1d655b58f88>,
 <pymongo.results.UpdateResult at 0x1d655b5b108>,
 <pymongo.results.UpdateResult at 0x1d655b5be88>,
 <pymongo.results.UpdateResult at 0x1d655b5f148>,
 <pymongo.results.UpdateResult at 0x1d655b5fe48>]

In [124]:
# Get data from mongo & convert back to dataframe
df = pd.DataFrame.from_records(db.population.find({}, {'_id': 0 }))
df

,Category,Created_By,Created_Date,Description,H_Name,Hierarchy,Notes,Population_Number,SubCategory,Year
0,Population,Charleen,05-05-2019 08:11:08,Integer,Alabama,State,,4633360.0,Total,2009
1,Population,Charleen,05-05-2019 08:11:08,Integer,Alaska,State,,683142.0,Total,2009
2,Population,Charleen,05-05-2019 08:11:08,Integer,Arizona,State,,6324865.0,Total,2009
3,Population,Charleen,05-05-2019 08:11:08,Integer,Arkansas,State,,2838143.0,Total,2009
4,Population,Charleen,05-05-2019 08:11:08,Integer,California,State,,36308527.0,Total,2009
5,Population,Charleen,05-05-2019 08:11:08,Integer,Colorado,State,,4843211.0,Total,2009
6,Population,Charleen,05-05-2019 08:11:08,Integer,Connecticut,State,,3494487.0,Total,2009
7,Population,Charleen,05-05-2019 08:11:08,Integer,Delaware,State,,863832.0,Total,2009
8,Population,Charleen,05-05-2019 08:11:08,Integer,District of Columbia,State,,588433.0,Total,2009
9,Population,Charleen,05-05-2019 08:11:08,Integer,Florida,State,,18222420.0,Total,2009
10,Population,Charleen,05-05-2019 08:11:08,Integer,Georgia,State,,9497667.0,Total,2009
11,Population,Charleen,05-05-2019 08:11:08,Integer,Hawaii,State,,1280241.0,Total,2009
12,Population,Charleen,05-05-2019 08:11:08,Integer,Idaho,State,,1492573.0,Total,2009
13,Population,Charleen,05-05-2019 08:11:08,Integer,Illinois,State,,12785043.0,Total,2009
14,Population,Charleen,05-05-2019 08:11:08,Integer,Indiana,State,,6342469.0,Total,2009
15,Population,Charleen,05-05-2019 08:11:08,Integer,Iowa,State,,2978880.0,Total,2009
16,Population,Charleen,05-05-2019 08:11:08,Integer,Kansas,State,,2777835.0,Total,2009
17,Population,Charleen,05-05-2019 08:11:08,Integer,Kentucky,State,,4252000.0,Total,2009
18,Population,Charleen,05-05-2019 08:11:08,Integer,Louisiana,State,,4411546.0,Total,2009
19,Population,Charleen,05-05-2019 08:11:08,Integer,Maine,State,,1316380.0,Total,2009
20,Population,Charleen,05-05-2019 08:11:08,Integer,Maryland,State,,5637418.0,Total,2009
21,Population,Charleen,05-05-2019 08:11:08,Integer,Massachusetts,State,,6511176.0,Total,2009
22,Population,Charleen,05-05-2019 08:11:08,Integer,Michigan,State,,10039208.0,Total,2009
23,Population,Charleen,05-05-2019 08:11:08,Integer,Minnesota,State,,5188581.0,Total,2009
24,Population,Charleen,05-05-2019 08:11:08,Integer,Mississippi,State,,2922240.0,Total,2009
25,Population,Charleen,05-05-2019 08:11:08,Integer,Missouri,State,,5904382.0,Total,2009
26,Population,Charleen,05-05-2019 08:11:08,Integer,Montana,State,,956257.0,Total,2009
27,Population,Charleen,05-05-2019 08:11:08,Integer,Nebraska,State,,1772124.0,Total,2009
28,Population,Charleen,05-05-2019 08:11:08,Integer,Nevada,State,,2545763.0,Total,2009
29,Population,Charleen,05-05-2019 08:11:08,Integer,New Hampshire,State,,1315419.0,Total,2009
...,...,...,...,...,...,...,...,...,...,...
4152,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Massachusetts,State,,78.9,White,2017
4153,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Michigan,State,,78.7,White,2017
4154,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Minnesota,State,,83.7,White,2017
4155,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Mississippi,State,,58.8,White,2017
4156,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Missouri,State,,82.4,White,2017
4157,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Montana,State,,89.0,White,2017
4158,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Nebraska,State,,87.8,White,2017
4159,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Nevada,State,,67.1,White,2017
4160,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,New Hampshire,State,,93.4,White,2017
4161,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,New Jersey,State,,67.9,White,2017
4162,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,New Mexico,State,,74.2,White,2017
4163,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,New York,State,,63.8,White,2017
4164,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,North Carolina,State,,69.0,White,2017
4165,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,North Dakota,State,,87.7,White,2017
4166,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Ohio,State,,81.9,White,2017
4167,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Oklahoma,State,,72.6,White,2017
4168,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Oregon,State,,84.9,White,2017
4169,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Pennsylvania,State,,81.1,White,2017
4170,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Rhode Island,State,,80.9,White,2017
4171,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,South Carolina,State,,67.3,White,2017
4172,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,South Dakota,State,,84.7,White,2017
4173,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Tennessee,State,,77.8,White,2017
4174,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Texas,State,,74.6,White,2017
4175,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Utah,State,,86.8,White,2017
4176,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Vermont,State,,94.5,White,2017
4177,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Virginia,State,,68.4,White,2017
4178,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Washington,State,,76.7,White,2017
4179,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,West Virginia,State,,93.3,White,2017
4180,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Wisconsin,State,,85.9,White,2017
4181,Ethnicity,Charleen,05-07-2019 06:55:45,Percentage,Wyoming,State,,91.3,White,2017

In [125]:
# db.population.drop()