In [158]:
# Dependencies
import os
import sys
import re 
import pandas as pd
import numpy as np
from pymongo import MongoClient
import shutil
pd.options.mode.chained_assignment = None  # default='warn'

In [159]:
# Set directory file paths
filepath = os.path.join(".", "Resources/State/Demographic", "ACS_13_5YR_S0102_with_ann.csv")

In [160]:
total_state_df = pd.read_csv(filepath, skiprows=[0])
# Split the extension from the path and normalise it to lowercase.
# ext = os.path.splitext(filepath)[-1].lower()
# excel = os.path.splitext(filepath)[0].lower()

# state_df["Year"] = "2009"
# state_df["Year"] = int(excel.split("_")[-1])
total_state_df.head()

,Id,Id2,Geography,Total; Estimate; Total population,Total; Margin of Error; Total population,60 years and over; Estimate; Total population,60 years and over; Margin of Error; Total population,Total; Estimate; SEX AND AGE - Male,Total; Margin of Error; SEX AND AGE - Male,60 years and over; Estimate; SEX AND AGE - Male,...,60 years and over; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Less than 30 percent,60 years and over; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Less than 30 percent,Total; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,Total; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,60 years and over; Estimate; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,60 years and over; Margin of Error; Renter-occupied housing units - GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - 30 percent or more,Total; Estimate; GROSS RENT - Median gross rent (dollars),Total; Margin of Error; GROSS RENT - Median gross rent (dollars),60 years and over; Estimate; GROSS RENT - Median gross rent (dollars),60 years and over; Margin of Error; GROSS RENT - Median gross rent (dollars)
0,0400000US01,1,Alabama,4799277,*****,966454,2674,48.5,0.1,44.1,...,56.0,1.0,44.8,0.6,44.0,1.0,705,3,569,9
1,0400000US02,2,Alaska,720316,*****,96430,985,52.2,0.1,50.3,...,52.6,2.7,40.6,0.9,47.4,2.7,1098,13,846,23
2,0400000US04,4,Arizona,6479703,*****,1294109,3052,49.7,0.1,46.1,...,46.1,0.9,47.5,0.4,53.9,0.9,896,4,836,8
3,0400000US05,5,Arkansas,2933369,*****,601493,2218,49.1,0.1,44.9,...,58.1,1.3,43.0,0.6,41.9,1.3,661,4,565,9
4,0400000US06,6,California,37659181,*****,6360929,7359,49.7,0.1,45.0,...,40.2,0.3,54.1,0.2,59.8,0.3,1224,2,994,4

In [161]:
demo_state_cols_df = total_state_df.filter(regex="RACE AND HISPANIC OR LATINO ORIGIN")
demo_state_df = total_state_df.filter(regex="Geography")

demo_state_df.head()
demo_state_cols_df.head()

,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races
0,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,0.1,...,0.0,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1
1,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,0.1,...,0.5,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3
2,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,0.1,...,0.1,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1
3,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,0.1,...,0.0,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1
4,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,0.1,...,0.3,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1

In [162]:
total_demo_state_df = pd.concat([demo_state_df, demo_state_cols_df], axis=1)

total_demo_state_df.head()

,Geography,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,0.0,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,0.5,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,0.1,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,0.0,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,0.3,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1

In [163]:
total_demo_state_df["Year"] = "2013"
# state_df["Year"] = int(excel.split("_")[-1])
total_demo_state_df.head()

,Geography,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Year
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,0.1,1.2,0.1,0.2,0.1,1.5,0.1,0.8,0.1,2013
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,0.1,1.2,0.1,0.6,0.2,7.9,0.2,2.4,0.3,2013
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,0.1,6.2,0.1,2.4,0.1,3.0,0.1,1.0,0.1,2013
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,0.1,2.2,0.1,0.4,0.1,2.0,0.1,1.1,0.1,2013
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,0.1,12.9,0.1,5.4,0.1,4.3,0.1,1.9,0.1,2013

In [164]:
total_demo_state_df.columns

Index(['Geography',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - American Indian and Alaska Native',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Asian',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Native Hawaiian and Other Pacific Islander',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - Some other race',
       'Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       'Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       '60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       '60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races',
       'Year'],
      dtype='object')

In [165]:
# Pass sheet title to description & country to hierachy columns for each row
total_demo_state_df["Hierarchy"] = "State"
# state_df["H_Name"] = list(state_df)[2]
# state_df["Population_Number"] = list(state_df)[3]
total_demo_state_df["Category"] = "Ethnicity"
total_demo_state_df["SubCategory"] = "White"
total_demo_state_df["Description"] = "Percentage"
total_demo_state_df["Notes"] = ""

# Rename 1st two columns
mapping = {state_df.columns[0]: 'H_Name', total_dstate_df.columns[5]: 'Population_Number'}
state_df = state_df.rename(columns=mapping)

state_df.head()

,H_Name,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,Population_Number,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race,Population_Number,Population_Number,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - One race - White,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - One race - Black or African American,...,Total; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Total; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Estimate; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,60 years and over; Margin of Error; RACE AND HISPANIC OR LATINO ORIGIN - Two or more races,Year,Hierarchy,Category,SubCategory,Description,Notes
0,Alabama,98.5,0.1,99.2,0.1,69.3,0.1,78.9,0.1,26.3,...,1.5,0.1,0.8,0.1,2013,State,Ethnicity,White,Percentage,
1,Alaska,92.1,0.2,97.6,0.3,66.9,0.1,76.8,0.4,3.5,...,7.9,0.2,2.4,0.3,2013,State,Ethnicity,White,Percentage,
2,Arizona,97.0,0.1,99.0,0.1,79.2,0.2,90.1,0.1,4.2,...,3.0,0.1,1.0,0.1,2013,State,Ethnicity,White,Percentage,
3,Arkansas,98.0,0.1,98.9,0.1,78.3,0.1,87.6,0.1,15.5,...,2.0,0.1,1.1,0.1,2013,State,Ethnicity,White,Percentage,
4,California,95.7,0.1,98.1,0.1,62.3,0.1,72.6,0.1,6.0,...,4.3,0.1,1.9,0.1,2013,State,Ethnicity,White,Percentage,

In [145]:
final_state_df = state_df[['Year', 'Hierarchy', 'H_Name', 'Population_Number', 'Category', 'SubCategory', 'Description', 'Notes']]
final_state_df.head()

,Year,Hierarchy,H_Name,Population_Number,Category,SubCategory,Description,Notes
0,2013,State,Alabama,0.1,Ethnicity,White,Percentage,
1,2013,State,Alaska,0.2,Ethnicity,White,Percentage,
2,2013,State,Arizona,0.1,Ethnicity,White,Percentage,
3,2013,State,Arkansas,0.1,Ethnicity,White,Percentage,
4,2013,State,California,0.1,Ethnicity,White,Percentage,

In [146]:
# This function move footnotes to specific cells and remove Nan rows
def Update_FootNotes(_df):
    _df["Notes"] = "" 
    # Get all the 1st character in column, extract only digit & get the max    
    nlist = _df['Notes'].str[0].tolist()
    results = [int(n) for n in nlist if n.isdigit()]
    m = max(results)
    f = m
    # Loop thru the max and update footnote to specific row cell
    for i in range(m):
        n = (i+1)
        fn = f'-{f}'
        #         print(n)
        #         print(fn)
        footnote = _df.iloc[int(fn), 0].replace(f"{n} ", "")
#         print(footnote)
        _df.loc[_df.Notes.str.contains(str(n)), "Notes"] = f'Footnotes {n}: {footnote}'
        f-=1
    # -----------------------------------------------    
    # Drop all NaN rows
    _df = _df.dropna()
    # Remove digit from column
    pattern = '[0-9]'
    _df.Notes = [re.sub(pattern, '', row.Notes) for i, row in _df.iterrows()] 
        
    return _df

In [147]:
# Pass footnote to specific cells and clean data
# state_df = Update_FootNotes(state_df)
# Convert Column to Integer
# state_df[""] = state_df[""].astype(int)
# Some excel sheet has lowercase
# state_df.loc[state_df[""] == "", ""] = ""
# state_df.reset_index(drop=True,inplace=True)

In [148]:
final_state_df["Created_By"] = "Charleen"
final_state_df["Created_Date"] = pd.datetime.now().strftime("%m-%d-%Y %I:%M:%S")
final_state_df.head()

,Year,Hierarchy,H_Name,Population_Number,Category,SubCategory,Description,Notes,Created_By,Created_Date
0,2013,State,Alabama,0.1,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:27:15
1,2013,State,Alaska,0.2,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:27:15
2,2013,State,Arizona,0.1,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:27:15
3,2013,State,Arkansas,0.1,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:27:15
4,2013,State,California,0.1,Ethnicity,White,Percentage,,Charleen,05-07-2019 06:27:15

In [123]:
# # Create notes column and copy footnotes to Notes for selective row by locating the row cell with the footnote
# country_df["Notes"] = ""      
# country_df.loc[country_df.Crime_Type.str.contains('1'), "Notes"] = f'Footnotes: {country_df.iloc[-2, 0].replace("1 ", "")}'
# country_df.loc[country_df.Crime_Type.str.contains('2'), "Notes"] = f'Footnotes: {country_df.iloc[-1, 0].replace("2 ", "")}'
# # Drop all NaN rows
# country_df = country_df.dropna()
# # Remove digit from column
# pattern = '[0-9]'
# country_df.Crime_Type = [re.sub(pattern, '', row.Crime_Type) for i, row in country_df.iterrows()] 
final_state_df.count()

Year                 51
Hierarchy            51
H_Name               51
Population_Number    51
Category             51
SubCategory          51
Description          51
Notes                51
Created_By           51
Created_Date         51
dtype: int64

In [124]:
final_state_df.dtypes

Year                  object
Hierarchy             object
H_Name                object
Population_Number    float64
Category              object
SubCategory           object
Description           object
Notes                 object
Created_By            object
Created_Date          object
dtype: object

In [125]:
final_state_df['Year'] = final_state_df['Year'].astype(int)

In [126]:
final_state_df = final_state_df.astype({'Year': 'int64'})

In [127]:
final_state_df.dtypes

Year                   int64
Hierarchy             object
H_Name                object
Population_Number    float64
Category              object
SubCategory           object
Description           object
Notes                 object
Created_By            object
Created_Date          object
dtype: object

In [128]:
final_state_df['H_Name'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [129]:
len(final_state_df['H_Name'].unique())

51

In [130]:
final_state_df.shape

(51, 10)

In [131]:
final_state_df.describe()

         Year  Population_Number
count    51.0          51.000000
mean   2017.0          96.623529
std       0.0           3.203660
min    2017.0          76.200000
25%    2017.0          96.850000
50%    2017.0          97.400000
75%    2017.0          97.700000
max    2017.0          98.700000

In [132]:
# Set connection to database
client = MongoClient("mongodb+srv://admin:admin123@janie-test-vcn3t.mongodb.net/test?retryWrites=true")
db = client.consultant

In [133]:
records = final_state_df.to_dict('records')
[db.population.update_many({"Year": row["Year"], "Hierarchy": row["Hierarchy"], "H_Name": row["H_Name"], "Population_Number": row["Population_Number"], "Category": row["Category"], "SubCategory": row["SubCategory"], "Description": row["Description"], "Notes": row["Notes"], "Created_By": row["Created_By"], "Created_Date": row["Created_Date"]}, {'$set': row}, upsert=True) for row in records]

[<pymongo.results.UpdateResult at 0x1c2e8d43e48>,
 <pymongo.results.UpdateResult at 0x1c2e8e0ddc8>,
 <pymongo.results.UpdateResult at 0x1c2e8d9fa08>,
 <pymongo.results.UpdateResult at 0x1c2e8dee388>,
 <pymongo.results.UpdateResult at 0x1c2e8df41c8>,
 <pymongo.results.UpdateResult at 0x1c2e8e09248>,
 <pymongo.results.UpdateResult at 0x1c2e8e09848>,
 <pymongo.results.UpdateResult at 0x1c2e8e09b88>,
 <pymongo.results.UpdateResult at 0x1c2e8d451c8>,
 <pymongo.results.UpdateResult at 0x1c2e8df4ec8>,
 <pymongo.results.UpdateResult at 0x1c2e8dfd288>,
 <pymongo.results.UpdateResult at 0x1c2e8df5588>,
 <pymongo.results.UpdateResult at 0x1c2e8df5888>,
 <pymongo.results.UpdateResult at 0x1c2e8df97c8>,
 <pymongo.results.UpdateResult at 0x1c2e8df9808>,
 <pymongo.results.UpdateResult at 0x1c2e8dab4c8>,
 <pymongo.results.UpdateResult at 0x1c2e8de5488>,
 <pymongo.results.UpdateResult at 0x1c2e8de5408>,
 <pymongo.results.UpdateResult at 0x1c2e8de79c8>,
 <pymongo.results.UpdateResult at 0x1c2e8de7e88>,
 <pymongo.results.UpdateResult at 0x1c2e8df0d48>,
 <pymongo.results.UpdateResult at 0x1c2e8df0888>,
 <pymongo.results.UpdateResult at 0x1c2e8de1c48>,
 <pymongo.results.UpdateResult at 0x1c2e8dff6c8>,
 <pymongo.results.UpdateResult at 0x1c2e8dff688>,
 <pymongo.results.UpdateResult at 0x1c2e8e02888>,
 <pymongo.results.UpdateResult at 0x1c2e8e02e48>,
 <pymongo.results.UpdateResult at 0x1c2e8db1048>,
 <pymongo.results.UpdateResult at 0x1c2e8db1648>,
 <pymongo.results.UpdateResult at 0x1c2e8e38188>,
 <pymongo.results.UpdateResult at 0x1c2e8e38e48>,
 <pymongo.results.UpdateResult at 0x1c2e8e3b1c8>,
 <pymongo.results.UpdateResult at 0x1c2e8e3bd48>,
 <pymongo.results.UpdateResult at 0x1c2e8e1cb48>,
 <pymongo.results.UpdateResult at 0x1c2e8e1c988>,
 <pymongo.results.UpdateResult at 0x1c2e8e3dbc8>,
 <pymongo.results.UpdateResult at 0x1c2e8e3df08>,
 <pymongo.results.UpdateResult at 0x1c2e8e41708>,
 <pymongo.results.UpdateResult at 0x1c2e8e41a48>,
 <pymongo.results.UpdateResult at 0x1c2e8e436c8>,
 <pymongo.results.UpdateResult at 0x1c2e8e43548>,
 <pymongo.results.UpdateResult at 0x1c2e8e47848>,
 <pymongo.results.UpdateResult at 0x1c2e8e47ec8>,
 <pymongo.results.UpdateResult at 0x1c2e8e4a088>,
 <pymongo.results.UpdateResult at 0x1c2e8e4ac88>,
 <pymongo.results.UpdateResult at 0x1c2e8e4c248>,
 <pymongo.results.UpdateResult at 0x1c2e8e4cc88>,
 <pymongo.results.UpdateResult at 0x1c2e8e50288>,
 <pymongo.results.UpdateResult at 0x1c2e8e50788>,
 <pymongo.results.UpdateResult at 0x1c2e8e52088>,
 <pymongo.results.UpdateResult at 0x1c2e8e52dc8>]

In [134]:
# Get data from mongo & convert back to dataframe
df = pd.DataFrame.from_records(db.population.find({}, {'_id': 0 }))
df

,Category,Created_By,Created_Date,Description,H_Name,Hierarchy,Notes,Population_Number,SubCategory,Year
0,Population,Charleen,05-05-2019 08:11:08,Integer,Alabama,State,,4633360.0,Total,2009
1,Population,Charleen,05-05-2019 08:11:08,Integer,Alaska,State,,683142.0,Total,2009
2,Population,Charleen,05-05-2019 08:11:08,Integer,Arizona,State,,6324865.0,Total,2009
3,Population,Charleen,05-05-2019 08:11:08,Integer,Arkansas,State,,2838143.0,Total,2009
4,Population,Charleen,05-05-2019 08:11:08,Integer,California,State,,36308527.0,Total,2009
5,Population,Charleen,05-05-2019 08:11:08,Integer,Colorado,State,,4843211.0,Total,2009
6,Population,Charleen,05-05-2019 08:11:08,Integer,Connecticut,State,,3494487.0,Total,2009
7,Population,Charleen,05-05-2019 08:11:08,Integer,Delaware,State,,863832.0,Total,2009
8,Population,Charleen,05-05-2019 08:11:08,Integer,District of Columbia,State,,588433.0,Total,2009
9,Population,Charleen,05-05-2019 08:11:08,Integer,Florida,State,,18222420.0,Total,2009
10,Population,Charleen,05-05-2019 08:11:08,Integer,Georgia,State,,9497667.0,Total,2009
11,Population,Charleen,05-05-2019 08:11:08,Integer,Hawaii,State,,1280241.0,Total,2009
12,Population,Charleen,05-05-2019 08:11:08,Integer,Idaho,State,,1492573.0,Total,2009
13,Population,Charleen,05-05-2019 08:11:08,Integer,Illinois,State,,12785043.0,Total,2009
14,Population,Charleen,05-05-2019 08:11:08,Integer,Indiana,State,,6342469.0,Total,2009
15,Population,Charleen,05-05-2019 08:11:08,Integer,Iowa,State,,2978880.0,Total,2009
16,Population,Charleen,05-05-2019 08:11:08,Integer,Kansas,State,,2777835.0,Total,2009
17,Population,Charleen,05-05-2019 08:11:08,Integer,Kentucky,State,,4252000.0,Total,2009
18,Population,Charleen,05-05-2019 08:11:08,Integer,Louisiana,State,,4411546.0,Total,2009
19,Population,Charleen,05-05-2019 08:11:08,Integer,Maine,State,,1316380.0,Total,2009
20,Population,Charleen,05-05-2019 08:11:08,Integer,Maryland,State,,5637418.0,Total,2009
21,Population,Charleen,05-05-2019 08:11:08,Integer,Massachusetts,State,,6511176.0,Total,2009
22,Population,Charleen,05-05-2019 08:11:08,Integer,Michigan,State,,10039208.0,Total,2009
23,Population,Charleen,05-05-2019 08:11:08,Integer,Minnesota,State,,5188581.0,Total,2009
24,Population,Charleen,05-05-2019 08:11:08,Integer,Mississippi,State,,2922240.0,Total,2009
25,Population,Charleen,05-05-2019 08:11:08,Integer,Missouri,State,,5904382.0,Total,2009
26,Population,Charleen,05-05-2019 08:11:08,Integer,Montana,State,,956257.0,Total,2009
27,Population,Charleen,05-05-2019 08:11:08,Integer,Nebraska,State,,1772124.0,Total,2009
28,Population,Charleen,05-05-2019 08:11:08,Integer,Nevada,State,,2545763.0,Total,2009
29,Population,Charleen,05-05-2019 08:11:08,Integer,New Hampshire,State,,1315419.0,Total,2009
...,...,...,...,...,...,...,...,...,...,...
3897,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Massachusetts,State,,96.9,Total,2017
3898,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Michigan,State,,97.2,Total,2017
3899,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Minnesota,State,,97.2,Total,2017
3900,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Mississippi,State,,98.7,Total,2017
3901,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Missouri,State,,97.5,Total,2017
3902,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Montana,State,,97.2,Total,2017
3903,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Nebraska,State,,97.6,Total,2017
3904,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Nevada,State,,95.3,Total,2017
3905,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,New Hampshire,State,,98.0,Total,2017
3906,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,New Jersey,State,,97.4,Total,2017
3907,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,New Mexico,State,,96.7,Total,2017
3908,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,New York,State,,97.0,Total,2017
3909,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,North Carolina,State,,97.5,Total,2017
3910,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,North Dakota,State,,97.7,Total,2017
3911,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Ohio,State,,97.3,Total,2017
3912,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Oklahoma,State,,92.2,Total,2017
3913,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Oregon,State,,95.4,Total,2017
3914,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Pennsylvania,State,,97.7,Total,2017
3915,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Rhode Island,State,,97.0,Total,2017
3916,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,South Carolina,State,,97.9,Total,2017
3917,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,South Dakota,State,,97.3,Total,2017
3918,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Tennessee,State,,97.9,Total,2017
3919,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Texas,State,,97.4,Total,2017
3920,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Utah,State,,97.2,Total,2017
3921,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Vermont,State,,98.1,Total,2017
3922,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Virginia,State,,96.5,Total,2017
3923,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Washington,State,,94.5,Total,2017
3924,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,West Virginia,State,,98.3,Total,2017
3925,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Wisconsin,State,,97.7,Total,2017
3926,Ethnicity,Charleen,05-07-2019 06:20:18,Percentage,Wyoming,State,,97.4,Total,2017

In [135]:
# db.population.drop()